runtime: python312
default_expiration: "7d"
instance_class: B4

basic_scaling:
  max_instances: 1
  idle_timeout: 5m

handlers:

- url: /static
  static_dir: givefood/static
  http_headers:
    Strict-Transport-Security: max-age=63072000; includeSubDomains; preload

- url: /_ah/(mapreduce|queue|warmup|start|stop).*
  script: auto
  login: admin

- url: /_ah/internalupload.*
  script: auto

- url: /favicon.ico
  static_files: givefood/static/img/favicon.ico
  upload: givefood/static/img/favicon.ico

- url: /security.txt
  static_files: givefood/static/root/security.txt
  upload: givefood/static/root/security.txt

- url: /humans.txt
  static_files: givefood/static/root/humans.txt
  upload: givefood/static/root/humans.txt

- url: /offline.*
  script: auto
  login: admin

- url: /admin.*
  script: auto

- url: /.*
  script: auto