runtime: python38
default_expiration: "7d"
instance_class: F2

handlers:

- url: /static
  static_dir: givefood/static
  http_headers:
    Strict-Transport-Security: max-age=63072000; includeSubDomains; preload

- url: /_ah/(mapreduce|queue|warmup|start|stop).*
  script: auto
  login: admin

- url: /_ah/internalupload.*
  script: auto

- url: /static/img/map-allloc.png
  script: auto

- url: /favicon.ico
  static_files: givefood/static/img/favicon.ico
  upload: givefood/static/img/favicon.ico

- url: /needs/manifest.json
  static_files: givefood/static/wfbn_manifest.json
  upload: givefood/static/wfbn_manifest.json

- url: /robots.txt
  static_files: givefood/static/root/robots.txt
  upload: givefood/static/root/robots.txt

- url: /security.txt
  static_files: givefood/static/root/security.txt
  upload: givefood/static/root/security.txt

- url: /humans.txt
  static_files: givefood/static/root/humans.txt
  upload: givefood/static/root/humans.txt

- url: /offline.*
  script: auto
  login: admin

- url: /admin.*
  script: auto
  login: admin

- url: /generate-(2019|2020|2021)/$
  script: auto
  login: admin

- url: /.*
  script: auto