SECONDS_IN_MINUTE = 60
SECONDS_IN_TWO_MINUTES = 120
SECONDS_IN_HALF_HOUR = 30 * SECONDS_IN_MINUTE
SECONDS_IN_HOUR = 60 * SECONDS_IN_MINUTE
SECONDS_IN_DAY = 24 * SECONDS_IN_HOUR
SECONDS_IN_WEEK = 7 * SECONDS_IN_DAY
SECONDS_IN_MONTH = 4 * SECONDS_IN_WEEK