ITEM_CATEGORY_GROUPS = {
    "Tinned Tomatoes": "Meal Food",
    "Tinned Meat": "Meal Food",
    "Tinned Vegetarian": "Meal Food",
    "Tinned Pasta": "Meal Food",
    "Confectionery": "Snack Food",
    "Cereal": "Meal Food",
    "Tinned Fruit": "Meal Food",
    "Cheese": "Meal Food",
    "Milk": "Drink",
    "Fruit Juice": "Drink",
    "Squash": "Drink",
    "Condiment": "Cooking",
    "Noodles": "Meal Food",
    "Cooking Oil": "Cooking",
    "Tinned Fish": "Meal Food",
    "Soup": "Meal Food",
    "Crisps": "Snack Food",
    "Biscuits": "Snack Food",
    "Baked Beans": "Meal Food",
    "Tinned Vegetables": "Meal Food",
    "Pasta Sauce": "Cooking",
    "Pasta": "Meal Food",
    "Rice": "Meal Food",
    "Tea": "Drink",
    "Coffee": "Drink",
    "Sugar": "Cooking",
    "Spread": "Meal Food",
    "Vegetable": "Meal Food",
    "Instant Mash": "Meal Food",
    "Flour": "Cooking",
    "Stock": "Cooking",
    "Dessert": "Meal Food",
    "Washing Up Liquid": "Cleaning",
    "Toilet Roll": "Toiletries",
    "Shower Gel": "Toiletries",
    "Shampoo": "Toiletries",
    "Soap": "Toiletries",
    "Toothpaste/Mouthwash": "Toiletries",
    "Toothbrush": "Toiletries",
    "Deodorant": "Toiletries",
    "Laundry": "Cleaning",
    "Sanitary Products": "Toiletries",
    "Baby Food": "Baby Supplies",
    "Baby Milk": "Baby Supplies",
    "Nappies": "Baby Supplies",
    "Wipes": "Baby Supplies",
    "Kitchen Roll": "Cleaning",
    "Household Supplies": "Cleaning",
    "Pet Food": "Other",
    "Carrier Bags": "Other",
    "Sauce": "Cooking",
    "Other": "Other",
    "Toiletries": "Toiletries",
    "Hot Chocolate": "Drink",
}

ITEM_GROUPS = list(ITEM_CATEGORY_GROUPS.values())
ITEM_GROUPS.sort()
ITEM_GROUPS_CHOICES = tuple((group, group) for group in ITEM_GROUPS)

ITEM_CATEGORIES = list(ITEM_CATEGORY_GROUPS.keys())
ITEM_CATEGORIES.sort()
ITEM_CATEGORIES_CHOICES = tuple((category, category) for category in ITEM_CATEGORIES)
