TOMATOES = [
    "Grower's Harvest Chopped Tomatoes 400G",
    "Grower's Harvest Plum Tomatoes 400G",
    "Tesco Everyday Value Plum Tomatoes 400G",
    "Hubbard?s Foodstore Chopped Tomatoes 400g",
    "Napolina Chopped Tomatoes 4 X 400G",
    "Summer Pride Chopped Tomatoes 400G",
    "Sainsbury's Chopped Tomatoes 227g",
    "Sainsbury's Chopped Tomatoes Can 400g",
    "Sainsbury's Chopped Tomatoes With Herbs 227g",
    "Sainsbury's Italian Plum Tomatoes 400g",
]
RICE = [
    "Grower Harvest Long Grain Rice 1Kg",
    "Tesco Easy Cook Long Grain Rice 500G",
    "Hearty Food Co Golden Savoury Rice 120G",
    "Tesco Microwave Egg Fried Rice 250G",
    "Tesco Microwave Basmati Rice 250G",
    "Tesco Easy Cook Boil In Bag Rice 4 X 125G",
    "Tesco Microwave Wholegrain Rice 250G",
    "Tesco Microwave Pilau Rice 250G",
    "Tesco Microwave Golden Vegetable Rice 250G",
    "Tesco Everyday Value Golden Vegetable Savoury Rice 120G",
    "Tesco Microwave Long Grain Rice 250G",
    "Tesco Everyday Value Long Grain Rice 1Kg",
    "Uncle Ben's Special Microwave Rice Savoury Chicken Flavoured 250g",
    "Sainsbury's Microwave Rice Thai 250g",
    "Sainsbury's Microwave Rice Spicy Mexican 250g",
    "Sainsbury's Microwave Rice Mushroom 250g",
    "Uncle Ben's Wholegrain Rice 500g",
    "Sainsbury's Microwave Pilau Rice With Spices, Cumin and Fennel Seeds P250g",
    "Sainsbury's Microwave Rice Golden Vegetable 250g",
    "Uncle Ben's Boil in the Bag Rice Long Grain 500g",
    "Sainsbury's Savoury Rice, Golden Vegetable 105g",
    "Sainsbury's Beef Flavour Savoury Rice 105g",
    "Sainsbury's Boil In The Bag Brown Rice 4x125g",
]
PUDDINGS = [
    "Stockwell And Co. Rice Pudding 400G",
    "Stockwell And Co. Custard 385G",
    "Tesco Everyday Value Rice Pudding 400G",
    "Tesco Ready To Serve Custard 400G",
    "Tesco Everyday Value Ready To Serve Custard 385G",
    "Tesco Low Fat Creamy Custard 400G",
    "Stockwell & Co. Rice Pudding 400G",
    "Stockwell & Co. Custard 385G",
    "Sainsbury's Rice Pudding, Creamed 400g",
    "Hubbards Foodstore Rice Pudding 400g",
    "Ambrosia Low Fat Rice Pudding Can 400g",
    "Ambrosia Creamed Rice Pudding 4X125g",
    "Ambrosia Rice Pudding Can 400g",
    "Ambrosia Creamed Rice 400G Tin",
    "Ambrosia Devon Custard 750G",
    "Hubbard's Foodstore Custard 385g",
]
FRUIT = [
    "Tesco Pineapple Slices In Juice 227G",
    "Growers Harvest Mandarin Pieces In Syrup 312G",
    "Growers Harvest Peach Slices Syrup 410G",
    "Tesco Mandarin Segments In Juice 298G",
    "Growers Harvest Pineapple Pieces In Syrup 540G",
    "Tesco Grapefruit Segments In Juice 538G",
    "Tesco Ruby Red Grapefruit Segments In Juice 538G",
    "Tesco Everyday Value Pineapple Pieces Light Syrup 540G",
    "Tesco Sliced Peaches Light Syrup 410G",
]
SOUP = [
    "Stockwell And Co Vegetable Soup 400G",
    "Stockwell And Co Tomato Soup 400G",
    "Stockwell And Co Chicken Soup 400G",
    "Stockwell And Co Vegetable Soup In A Mug 4 Pack 72G",
    "Stockwell And Co Chicken And Vegetable Soup In A Mug 88G",
    "Tesco Cream Of Tomato Soup 295G",
    "Tesco Chicken Soup 295G",
    "Tesco Everyday Value Tomato Soup 400G",
    "Tesco Cream Of Tomato Soup 400G",
    "Tesco Cream Of Mushroom Soup 400G",
    "Tesco Broccoli And Stilton Soup 400G",
    "Tesco Everyday Value Vegetable Soup In A Mug 4 Pack 104G",
    "Tesco Potato And Leek Soup 400G",
    "Tesco Tomato Soup 295G",
    "Stockwell & Co Chicken Soup 400G",
    "Stockwell & Co Vegetable Soup 400G",
    "Stockwell & Co Tomato Soup 400G",
    "Tesco Minestrone Soup 400G",
    "Tesco Mulligatawny Soup 400G",
    "Tesco Pea And Ham Soup 400G",
    "Tesco Cream Of Chicken Soup 400G",
    "Tesco Potato & Leek Soup 400G",
    "Sainsbury's Chicken & Mushroom Soup 400g",
    "Sainsbury's Broccoli & Stilton Soup 400g",
    "Heinz Mushroom Soup 4x400g",
    "Sainsbury's Vegetable Soup 400g",
    "Heinz Vegetable Soup 4x400g",
    "Heinz No Added Sugar Cream Of Tomato Soup 4x400g",
    "Sainsbury's Scotch Broth Soup 400g",
    "Sainsbury's Cream Of Tomato Soup 400g",
    "Sainsbury's Cream Of Mushroom Soup 400g",
    "Sainsbury's Minestrone Soup 400g",
    "Sainsbury's Carrot & Coriander Soup 400g",
    "Heinz Oxtail Soup 4x400g",
    "Heinz Minestrone Soup 4x400g",
    "Sainsbury's Tomato & Basil Soup 400g",
    "Sainsbury's Tomato & Red Pepper Soup 400g",
    "Sainsbury's Cream Of Tomato Soup 4x400g",
    "Sainsbury's Spring Vegetable Soup 400g",
    "Heinz Cream of Tomato Soup x4 400g",
    "Sainsbury's Mulligatawny Soup 400g",
    "Heinz Classic Potato & Leek Soup 400g",
    "Sainsbury's Lentil & Bacon Soup 400g",
    "Sainsbury's Pea & Ham Soup 400g",
    "Sainsbury's Oxtail Soup 400g",
    "Sainsbury's Tomato Red Pepper & Lentil Soup 400g",
    "Sainsbury's Leek & Potato Soup 400g",
    "Sainsbury's Beef & Vegetable Soup 400g",
    "Sainsbury's Cream Of Chicken Soup 400g",
    "Sainsbury's Spiced Squash & Red Pepper Soup 400g",
    "Heinz Classic Cream of Chicken Soup 4x400g",
    "Sainsbury's Tomato & Spicy Lentil Soup, Be Good To Yourself 400g",
]
MILK = [
    "Creamfields Uht Semi Skimmed Milk 1 Litre",
    "Creamfields Uht Skimmed Milk 1 Litre",
    "Tesco British Whole Milk Longlife Uht 1 Litre",
    "Tesco British Skimmed Longlife Uht Milk 1 Litre",
    "Tesco British Semi Skimmed Longlife Uht Milk 1 Litre",
    "Tesco Everyday Value British Skimmed Longlife Uht Milk 1 Litre",
    "Tesco Everyday Value British Semi Skimmed Longlife Uht Milk 1 Litre",
    "Tesco British Semi Skimmed Longlife Uht Milk 500 Ml",
    "Sainsbury's Semi Skimmed British Milk 1L",
    "Sainsbury's Semi Skimmed Long Life Milk 6x1L",
    "Dairy Pride Semi-Skimmed Longer Lasting UHT Milk 1 Litre",
    "Sainsbury's Whole British Milk 1L",
]
FISH = [
    "Tesco Sardines In Tomato Sauce 120G",
]
VEG = [
    "Tesco Seasonal New Potatoes 750G",
]
NON_FOOD = [

]
MINCE_PIES = [
    "Tesco Mince Pies 6 Pack",
    "Tesco Lattice Mince Pies 6 Pack",
]
