parlcon_party = {
    "Morecambe and Lunesdale": "Conservative",
    "North East Hertfordshire": "Conservative",
    "Blaydon": "Labour",
    "Thornbury and Yate": "Conservative",
    "South Antrim": "DUP",
    "Belfast North": "Sinn F\xc3\xa9in",
    "Fermanagh and South Tyrone": "Sinn F\xc3\xa9in",
    "Ipswich": "Conservative",
    "Castle Point": "Conservative",
    "Rochdale": "Labour",
    "Neath": "Labour Co-operative",
    "Leeds West": "Labour",
    "South Leicestershire": "Conservative",
    "Ashton-under-Lyne": "Labour",
    "Epsom and Ewell": "Conservative",
    "Walsall North": "Conservative",
    "Penistone and Stocksbridge": "Conservative",
    "New Forest East": "Conservative",
    "Chipping Barnet": "Conservative",
    "Kilmarnock and Loudoun": "Scottish National",
    "Kettering": "Conservative",
    "Orkney and Shetland": "Liberal Democrats",
    "Aberavon": "Labour",
    "Rossendale and Darwen": "Conservative",
    "Angus": "Scottish National",
    "Westmorland and Lonsdale": "Liberal Democrats",
    "Solihull": "Conservative",
    "Totnes": "Conservative",
    "Manchester Withington": "Labour",
    "Garston and Halewood": "Labour",
    "Warwick and Leamington": "Labour",
    "Chesterfield": "Labour",
    "Dundee West": "Scottish National",
    "Exeter": "Labour",
    "Harwich and North Essex": "Conservative",
    "Bristol North West": "Labour",
    "Aberdeen South": "Scottish National",
    "Edmonton": "Labour Co-operative",
    "Hereford and South Herefordshire": "Conservative",
    "North East Bedfordshire": "Conservative",
    "Sheffield Central": "Labour",
    "Witham": "Conservative",
    "Lewisham Deptford": "Labour",
    "Eastbourne": "Conservative",
    "Heywood and Middleton": "Conservative",
    "Cardiff South and Penarth": "Labour Co-operative",
    "Southport": "Conservative",
    "Bolton South East": "Labour",
    "Vale of Glamorgan": "Conservative",
    "Bristol West": "Labour",
    "Derby North": "Conservative",
    "Winchester": "Conservative",
    "Staffordshire Moorlands": "Conservative",
    "Redditch": "Conservative",
    "Great Grimsby": "Conservative",
    "Milton Keynes North": "Conservative",
    "Ogmore": "Labour",
    "Wolverhampton South West": "Conservative",
    "Pendle": "Conservative",
    "Huddersfield": "Labour Co-operative",
    "City of Durham": "Labour",
    "Milton Keynes South": "Conservative",
    "Banff and Buchan": "Conservative",
    "Richmond (Yorks)": "Conservative",
    "Edinburgh South": "Labour",
    "Chippenham": "Conservative",
    "Buckingham": "Conservative",
    "Dumfriesshire, Clydesdale and Tweeddale": "Conservative",
    "Bradford East": "Labour",
    "North Dorset": "Conservative",
    "Halesowen and Rowley Regis": "Conservative",
    "Stourbridge": "Conservative",
    "Bury St Edmunds": "Conservative",
    "Battersea": "Labour",
    "Clwyd South": "Conservative",
    "High Peak": "Conservative",
    "Tooting": "Labour",
    "Stalybridge and Hyde": "Labour Co-operative",
    "Dudley North": "Conservative",
    "Oxford East": "Labour Co-operative",
    "South Basildon and East Thurrock": "Conservative",
    "Cardiff North": "Labour",
    "Luton South": "Labour",
    "Camborne and Redruth": "Conservative",
    "Alyn and Deeside": "Labour",
    "Sittingbourne and Sheppey": "Conservative",
    "Copeland": "Conservative",
    "Normanton, Pontefract and Castleford": "Labour",
    "Newton Abbot": "Conservative",
    "Hove": "Labour",
    "North West Hampshire": "Conservative",
    "Grantham and Stamford": "Conservative",
    "Chichester": "Conservative",
    "Mole Valley": "Conservative",
    "Bexleyheath and Crayford": "Conservative",
    "Tamworth": "Conservative",
    "South East Cornwall": "Conservative",
    "Brighton Pavilion": "Green",
    "Hitchin and Harpenden": "Conservative",
    "Bradford West": "Labour",
    "North Norfolk": "Conservative",
    "The Cotswolds": "Conservative",
    "Brentwood and Ongar": "Conservative",
    "Ynys M\xc3\xb4n": "Conservative",
    "Hammersmith": "Labour",
    "Mid Sussex": "Conservative",
    "Leeds North West": "Labour Co-operative",
    "Twickenham": "Liberal Democrats",
    "Henley": "Conservative",
    "Ashfield": "Conservative",
    "Kingston upon Hull North": "Labour",
    "Scunthorpe": "Conservative",
    "Liverpool Wavertree": "Labour",
    "Stretford and Urmston": "Labour",
    "South Swindon": "Conservative",
    "Cheltenham": "Conservative",
    "Mid Derbyshire": "Conservative",
    "North Down": "Alliance",
    "Bath": "Liberal Democrats",
    "Stoke-on-Trent North": "Conservative",
    "Stratford-on-Avon": "Conservative",
    "Hertsmere": "Conservative",
    "Leeds North East": "Labour",
    "St Albans": "Liberal Democrats",
    "Halifax": "Labour",
    "Brighton Kemptown": "Labour Co-operative",
    "Chelmsford": "Conservative",
    "North Shropshire": "Conservative",
    "Waveney": "Conservative",
    "Broxbourne": "Conservative",
    "Chatham and Aylesford": "Conservative",
    "Torfaen": "Labour",
    "Bassetlaw": "Conservative",
    "Forest of Dean": "Conservative",
    "Sheffield South East": "Labour",
    "Sefton Central": "Labour",
    "Wansbeck": "Labour",
    "Islington South and Finsbury": "Labour",
    "South Holland and The Deepings": "Conservative",
    "Sheffield Hallam": "Labour",
    "East Devon": "Conservative",
    "Mid Ulster": "Sinn F\xc3\xa9in",
    "Sheffield Brightside and Hillsborough": "Labour",
    "East Londonderry": "DUP",
    "Gower": "Labour",
    "Stafford": "Conservative",
    "Lanark and Hamilton East": "Scottish National",
    "Inverclyde": "Scottish National",
    "Harrow West": "Labour Co-operative",
    "Ealing North": "Labour Co-operative",
    "Stirling": "Scottish National",
    "Newcastle upon Tyne North": "Labour",
    "Lagan Valley": "DUP",
    "Crewe and Nantwich": "Conservative",
    "Walthamstow": "Labour Co-operative",
    "West Lancashire": "Labour",
    "Rushcliffe": "Conservative",
    "St Helens North": "Labour",
    "Great Yarmouth": "Conservative",
    "Reading East": "Labour",
    "Barnsley Central": "Labour",
    "South Cambridgeshire": "Conservative",
    "Welwyn Hatfield": "Conservative",
    "Southend West": "Conservative",
    "Beckenham": "Conservative",
    "Wyre and Preston North": "Conservative",
    "Dundee East": "Scottish National",
    "Salisbury": "Conservative",
    "Colne Valley": "Conservative",
    "Birmingham Erdington": "Labour",
    "Ilford North": "Labour",
    "Kirkcaldy and Cowdenbeath": "Scottish National",
    "Wyre Forest": "Conservative",
    "Peterborough": "Conservative",
    "Epping Forest": "Conservative",
    "South West Bedfordshire": "Conservative",
    "Wrexham": "Conservative",
    "Newark": "Conservative",
    "South Staffordshire": "Conservative",
    "Weston-Super-Mare": "Conservative",
    "Bournemouth East": "Conservative",
    "Bristol East": "Labour",
    "Weaver Vale": "Labour",
    "Glasgow South West": "Scottish National",
    "Northampton North": "Conservative",
    "Witney": "Conservative",
    "Ochil and South Perthshire": "Scottish National",
    "Llanelli": "Labour",
    "Rochester and Strood": "Conservative",
    "Gloucester": "Conservative",
    "Warrington North": "Labour",
    "Wirral West": "Labour",
    "Lewisham East": "Labour",
    "West Bromwich East": "Conservative",
    "Altrincham and Sale West": "Conservative",
    "Hendon": "Conservative",
    "Stockton South": "Conservative",
    "Middlesbrough South and East Cleveland": "Conservative",
    "Gordon": "Scottish National",
    "Brigg and Goole": "Conservative",
    "Louth and Horncastle": "Conservative",
    "Wallasey": "Labour",
    "Gateshead": "Labour",
    "Falkirk": "Scottish National",
    "Kensington": "Conservative",
    "Vale of Clwyd": "Conservative",
    "Somerton and Frome": "Conservative",
    "Oxford West and Abingdon": "Liberal Democrats",
    "Enfield Southgate": "Labour",
    "West Bromwich West": "Conservative",
    "Camberwell and Peckham": "Labour",
    "Hartlepool": "Conservative",
    "Dudley South": "Conservative",
    "Kenilworth and Southam": "Conservative",
    "Birmingham Perry Barr": "Labour",
    "Sevenoaks": "Conservative",
    "Truro and Falmouth": "Conservative",
    "Halton": "Labour",
    "Bradford South": "Labour",
    "Birmingham Ladywood": "Labour",
    "Glenrothes": "Scottish National",
    "Newcastle-under-Lyme": "Conservative",
    "Broadland": "Conservative",
    "Dewsbury": "Conservative",
    "South West Surrey": "Conservative",
    "Wigan": "Labour",
    "Finchley and Golders Green": "Conservative",
    "Rotherham": "Labour",
    "Coventry South": "Labour",
    "Feltham and Heston": "Labour Co-operative",
    "Stone": "Conservative",
    "Calder Valley": "Conservative",
    "Northampton South": "Conservative",
    "Barrow and Furness": "Conservative",
    "Harrow East": "Conservative",
    "Croydon South": "Conservative",
    "Tynemouth": "Labour",
    "Berwick-upon-Tweed": "Conservative",
    "Ross, Skye and Lochaber": "Scottish National",
    "Leicester South": "Labour Co-operative",
    "Beverley and Holderness": "Conservative",
    "Cambridge": "Labour",
    "Holborn and St Pancras": "Labour",
    "Woking": "Conservative",
    "Washington and Sunderland West": "Labour",
    "Motherwell and Wishaw": "Scottish National",
    "Romsey and Southampton North": "Conservative",
    "Coventry North East": "Labour",
    "Hornsey and Wood Green": "Labour",
    "East Renfrewshire": "Scottish National",
    "Sutton Coldfield": "Conservative",
    "North Durham": "Labour",
    "North West Durham": "Conservative",
    "Bristol South": "Labour",
    "Mid Worcestershire": "Conservative",
    "Dagenham and Rainham": "Labour",
    "Suffolk Coastal": "Conservative",
    "Newbury": "Conservative",
    "Birmingham Yardley": "Labour",
    "Loughborough": "Conservative",
    "Clwyd West": "Conservative",
    "Liverpool Walton": "Labour",
    "Haltemprice and Howden": "Conservative",
    "Gedling": "Conservative",
    "Carmarthen West and South Pembrokeshire": "Conservative",
    "South Shields": "Labour",
    "North Somerset": "Conservative",
    "Ayr, Carrick and Cumnock": "Scottish National",
    "Lincoln": "Conservative",
    "Swansea West": "Labour Co-operative",
    "Nottingham North": "Labour Co-operative",
    "Moray": "Conservative",
    "Belfast West": "Sinn F\xc3\xa9in",
    "Ceredigion": "Plaid Cymru",
    "Amber Valley": "Conservative",
    "Crawley": "Conservative",
    "Hampstead and Kilburn": "Labour",
    "Plymouth Moor View": "Conservative",
    "Caerphilly": "Labour",
    "Cannock Chase": "Conservative",
    "Bermondsey and Old Southwark": "Labour",
    "Derby South": "Labour",
    "Maidenhead": "Conservative",
    "Knowsley": "Labour",
    "Broxtowe": "Conservative",
    "Burton": "Conservative",
    "Hemsworth": "Labour",
    "Cynon Valley": "Labour",
    "North Herefordshire": "Conservative",
    "Ealing Southall": "Labour",
    "Wimbledon": "Conservative",
    "West Suffolk": "Conservative",
    "South Northamptonshire": "Conservative",
    "Runnymede and Weybridge": "Conservative",
    "Portsmouth North": "Conservative",
    "Erewash": "Conservative",
    "Aylesbury": "Conservative",
    "Blackpool North and Cleveleys": "Conservative",
    "Midlothian": "Scottish National",
    "Boston and Skegness": "Conservative",
    "Aberconwy": "Conservative",
    "Southampton Test": "Labour",
    "Worthing West": "Conservative",
    "Upper Bann": "DUP",
    "North East Derbyshire": "Conservative",
    "Meon Valley": "Conservative",
    "Stroud": "Conservative",
    "Bromley and Chislehurst": "Conservative",
    "Newry and Armagh": "Sinn F\xc3\xa9in",
    "Morley and Outwood": "Conservative",
    "Lancaster and Fleetwood": "Labour",
    "Guildford": "Conservative",
    "Plymouth Sutton and Devonport": "Labour Co-operative",
    "Birmingham Northfield": "Conservative",
    "Makerfield": "Labour",
    "Newcastle upon Tyne East": "Labour",
    "Fylde": "Conservative",
    "Rutland and Melton": "Conservative",
    "Ludlow": "Conservative",
    "North East Fife": "Liberal Democrats",
    "North Swindon": "Conservative",
    "Poole": "Conservative",
    "South Thanet": "Conservative",
    "Paisley and Renfrewshire North": "Scottish National",
    "Rhondda": "Labour",
    "Wycombe": "Conservative",
    "Wirral South": "Labour",
    "Barking": "Labour",
    "Tewkesbury": "Conservative",
    "Rayleigh and Wickford": "Conservative",
    "Huntingdon": "Conservative",
    "Fareham": "Conservative",
    "West Tyrone": "Sinn F\xc3\xa9in",
    "Bolsover": "Conservative",
    "Chingford and Woodford Green": "Conservative",
    "York Outer": "Conservative",
    "The Wrekin": "Conservative",
    "Tunbridge Wells": "Conservative",
    "Filton and Bradley Stoke": "Conservative",
    "Blaenau Gwent": "Labour",
    "Mid Norfolk": "Conservative",
    "Hackney South and Shoreditch": "Labour Co-operative",
    "Nottingham East": "Labour",
    "Ribble Valley": "Conservative",
    "Manchester Central": "Labour Co-operative",
    "Newcastle upon Tyne Central": "Labour",
    "Central Devon": "Conservative",
    "Stockport": "Labour",
    "York Central": "Labour Co-operative",
    "Arundel and South Downs": "Conservative",
    "North East Cambridgeshire": "Conservative",
    "Preseli Pembrokeshire": "Conservative",
    "Chesham and Amersham": "Conservative",
    "Ealing Central and Acton": "Labour",
    "Maidstone and The Weald": "Conservative",
    "Bedford": "Labour",
    "Thirsk and Malton": "Conservative",
    "Ruislip, Northwood and Pinner": "Conservative",
    "Kingston and Surbiton": "Liberal Democrats",
    "Spelthorne": "Conservative",
    "Wakefield": "Conservative",
    "Stockton North": "Labour",
    "Havant": "Conservative",
    "North Warwickshire": "Conservative",
    "Lewisham West and Penge": "Labour",
    "Wythenshawe and Sale East": "Labour",
    "Delyn": "Conservative",
    "Aldershot": "Conservative",
    "Windsor": "Conservative",
    "Oldham East and Saddleworth": "Labour",
    "Telford": "Conservative",
    "Mid Dorset and North Poole": "Conservative",
    "Sedgefield": "Conservative",
    "Darlington": "Conservative",
    "Stevenage": "Conservative",
    "Eddisbury": "Conservative",
    "Birmingham Selly Oak": "Labour",
    "Carshalton and Wallington": "Conservative",
    "Slough": "Labour",
    "North Thanet": "Conservative",
    "East Hampshire": "Conservative",
    "Easington": "Labour",
    "Leeds Central": "Labour",
    "Gravesham": "Conservative",
    "North Ayrshire and Arran": "Scottish National",
    "Colchester": "Conservative",
    "Arfon": "Plaid Cymru",
    "Harlow": "Conservative",
    "Doncaster North": "Labour",
    "Congleton": "Conservative",
    "Basingstoke": "Conservative",
    "Blackburn": "Labour",
    "Luton North": "Labour",
    "Yeovil": "Conservative",
    "Wokingham": "Conservative",
    "Blackpool South": "Conservative",
    "Horsham": "Conservative",
    "Newport West": "Labour",
    "Streatham": "Labour",
    "Lewes": "Conservative",
    "Wantage": "Conservative",
    "Richmond Park": "Liberal Democrats",
    "Scarborough and Whitby": "Conservative",
    "Middlesbrough": "Labour",
    "Watford": "Conservative",
    "Maldon": "Conservative",
    "Bishop Auckland": "Conservative",
    "Cardiff Central": "Labour",
    "Reigate": "Conservative",
    "Carlisle": "Conservative",
    "Berwickshire, Roxburgh and Selkirk": "Conservative",
    "Keighley": "Conservative",
    "Hayes and Harlington": "Labour",
    "Torbay": "Conservative",
    "Kingston upon Hull West and Hessle": "Labour",
    "Tiverton and Honiton": "Conservative",
    "Sherwood": "Conservative",
    "Blackley and Broughton": "Labour",
    "Inverness, Nairn, Badenoch and Strathspey": "Scottish National",
    "East Yorkshire": "Conservative",
    "Norwich South": "Labour",
    "Orpington": "Conservative",
    "Dartford": "Conservative",
    "Bury South": "Conservative",
    "Linlithgow and East Falkirk": "Scottish National",
    "Bracknell": "Conservative",
    "Monmouth": "Conservative",
    "Batley and Spen": "Labour Co-operative",
    "Foyle": "SDLP",
    "Chorley": "Speaker",
    "Mansfield": "Conservative",
    "Leyton and Wanstead": "Labour",
    "Daventry": "Conservative",
    "Hornchurch and Upminster": "Conservative",
    "Strangford": "DUP",
    "Glasgow Central": "Scottish National",
    "Bootle": "Labour",
    "Cleethorpes": "Conservative",
    "North Antrim": "DUP",
    "Devizes": "Conservative",
    "Nuneaton": "Conservative",
    "Enfield North": "Labour",
    "Hastings and Rye": "Conservative",
    "Livingston": "Scottish National",
    "Walsall South": "Labour",
    "Edinburgh East": "Scottish National",
    "Braintree": "Conservative",
    "Harrogate and Knaresborough": "Conservative",
    "Denton and Reddish": "Labour",
    "St Austell and Newquay": "Conservative",
    "Warley": "Labour",
    "Cardiff West": "Labour",
    "Esher and Walton": "Conservative",
    "Kingston upon Hull East": "Labour",
    "New Forest West": "Conservative",
    "Doncaster Central": "Labour",
    "South Derbyshire": "Conservative",
    "Brent Central": "Labour",
    "Belfast South": "SDLP",
    "Cumbernauld, Kilsyth and Kirkintilloch East": "Scottish National",
    "North Wiltshire": "Conservative",
    "East Ham": "Labour",
    "Bolton West": "Conservative",
    "Oldham West and Royton": "Labour Co-operative",
    "Aberdeen North": "Scottish National",
    "Ashford": "Conservative",
    "Beaconsfield": "Conservative",
    "North Devon": "Conservative",
    "Corby": "Conservative",
    "East Dunbartonshire": "Scottish National",
    "Greenwich and Woolwich": "Labour",
    "St Helens South and Whiston": "Labour",
    "East Antrim": "DUP",
    "Ellesmere Port and Neston": "Labour",
    "Paisley and Renfrewshire South": "Scottish National",
    "Edinburgh South West": "Scottish National",
    "Leicester East": "Labour",
    "South West Norfolk": "Conservative",
    "Leeds East": "Labour",
    "North Cornwall": "Conservative",
    "West Dunbartonshire": "Scottish National",
    "Pontypridd": "Labour",
    "Shipley": "Conservative",
    "Basildon and Billericay": "Conservative",
    "Brentford and Isleworth": "Labour",
    "Wentworth and Dearne": "Labour",
    "Islington North": "Labour",
    "Folkestone and Hythe": "Conservative",
    "Swansea East": "Labour",
    "Hazel Grove": "Conservative",
    "Hexham": "Conservative",
    "Mid Bedfordshire": "Conservative",
    "Pudsey": "Conservative",
    "East Kilbride, Strathaven and Lesmahagow": "Scottish National",
    "Liverpool Riverside": "Labour",
    "Stoke-on-Trent Central": "Conservative",
    "Harborough": "Conservative",
    "Workington": "Conservative",
    "Elmet and Rothwell": "Conservative",
    "Edinburgh North and Leith": "Scottish National",
    "Warrington South": "Conservative",
    "Stoke-on-Trent South": "Conservative",
    "Shrewsbury and Atcham": "Conservative",
    "Merthyr Tydfil and Rhymney": "Labour",
    "Glasgow South": "Scottish National",
    "North West Cambridgeshire": "Conservative",
    "Sheffield Heeley": "Labour",
    "Bromsgrove": "Conservative",
    "Edinburgh West": "Liberal Democrats",
    "Old Bexley and Sidcup": "Conservative",
    "Croydon Central": "Labour",
    "Thurrock": "Conservative",
    "Bosworth": "Conservative",
    "Chelsea and Fulham": "Conservative",
    "Rutherglen and Hamilton West": "Scottish National",
    "Hackney North and Stoke Newington": "Labour",
    "Charnwood": "Conservative",
    "North East Somerset": "Conservative",
    "East Worthing and Shoreham": "Conservative",
    "Christchurch": "Conservative",
    "Tonbridge and Malling": "Conservative",
    "South East Cambridgeshire": "Conservative",
    "Faversham and Mid Kent": "Conservative",
    "Don Valley": "Conservative",
    "Birmingham Hodge Hill": "Labour",
    "Glasgow North West": "Scottish National",
    "Cities of London and Westminster": "Conservative",
    "Tottenham": "Labour",
    "Putney": "Labour",
    "Selby and Ainsty": "Conservative",
    "Kingswood": "Conservative",
    "Brecon and Radnorshire": "Conservative",
    "Redcar": "Conservative",
    "Airdrie and Shotts": "Scottish National",
    "Southampton Itchen": "Conservative",
    "Blyth Valley": "Conservative",
    "Mitcham and Morden": "Labour",
    "Central Suffolk and North Ipswich": "Conservative",
    "Rugby": "Conservative",
    "Banbury": "Conservative",
    "Bexhill and Battle": "Conservative",
    "Hemel Hempstead": "Conservative",
    "Uxbridge and South Ruislip": "Conservative",
    "Hertford and Stortford": "Conservative",
    "Wealden": "Conservative",
    "Croydon North": "Labour Co-operative",
    "St Ives": "Conservative",
    "South Down": "Sinn F\xc3\xa9in",
    "Liverpool West Derby": "Labour",
    "Perth and North Perthshire": "Scottish National",
    "Dwyfor Meirionnydd": "Plaid Cymru",
    "Dunfermline and West Fife": "Scottish National",
    "Bolton North East": "Conservative",
    "Portsmouth South": "Labour",
    "Surrey Heath": "Conservative",
    "Leigh": "Conservative",
    "Houghton and Sunderland South": "Labour",
    "Sunderland Central": "Labour",
    "Hyndburn": "Conservative",
    "Bridgend": "Conservative",
    "West Worcestershire": "Conservative",
    "Bognor Regis and Littlehampton": "Conservative",
    "Rother Valley": "Conservative",
    "Tatton": "Conservative",
    "Manchester Gorton": "Labour",
    "East Lothian": "Scottish National",
    "Glasgow North": "Scottish National",
    "South West Wiltshire": "Conservative",
    "Meriden": "Conservative",
    "South Dorset": "Conservative",
    "Glasgow North East": "Scottish National",
    "Skipton and Ripon": "Conservative",
    "Worsley and Eccles South": "Labour",
    "Jarrow": "Labour",
    "Taunton Deane": "Conservative",
    "Coventry North West": "Labour",
    "Sleaford and North Hykeham": "Conservative",
    "Gainsborough": "Conservative",
    "Caithness, Sutherland and Easter Ross": "Liberal Democrats",
    "Na h-Eileanan an Iar": "Scottish National",
    "Macclesfield": "Conservative",
    "Bridgwater and West Somerset": "Conservative",
    "South Suffolk": "Conservative",
    "Erith and Thamesmead": "Labour",
    "South Ribble": "Conservative",
    "Reading West": "Conservative",
    "Torridge and West Devon": "Conservative",
    "Nottingham South": "Labour",
    "West Dorset": "Conservative",
    "Newport East": "Labour",
    "Bournemouth West": "Conservative",
    "Canterbury": "Labour",
    "Westminster North": "Labour",
    "North West Leicestershire": "Conservative",
    "South West Devon": "Conservative",
    "North West Norfolk": "Conservative",
    "Bury North": "Conservative",
    "Aldridge-Brownhills": "Conservative",
    "Montgomeryshire": "Conservative",
    "Preston": "Labour Co-operative",
    "Brent North": "Labour",
    "North Tyneside": "Labour",
    "North East Hampshire": "Conservative",
    "Birmingham Edgbaston": "Labour Co-operative",
    "East Surrey": "Conservative",
    "Penrith and The Border": "Conservative",
    "Romford": "Conservative",
    "Salford and Eccles": "Labour",
    "Wolverhampton South East": "Labour",
    "Bethnal Green and Bow": "Labour",
    "Vauxhall": "Labour Co-operative",
    "Central Ayrshire": "Scottish National",
    "Rochford and Southend East": "Conservative",
    "Argyll and Bute": "Scottish National",
    "Isle of Wight": "Conservative",
    "Wolverhampton North East": "Conservative",
    "Barnsley East": "Labour",
    "Belfast East": "DUP",
    "Gillingham and Rainham": "Conservative",
    "Islwyn": "Labour Co-operative",
    "Dulwich and West Norwood": "Labour",
    "Lichfield": "Conservative",
    "Birmingham Hall Green": "Labour",
    "Burnley": "Conservative",
    "Wells": "Conservative",
    "West Aberdeenshire and Kincardine": "Conservative",
    "Cheadle": "Conservative",
    "South West Hertfordshire": "Conservative",
    "Glasgow East": "Scottish National",
    "Leicester West": "Labour",
    "Wellingborough": "Conservative",
    "Gosport": "Conservative",
    "West Ham": "Labour",
    "Birkenhead": "Labour",
    "Poplar and Limehouse": "Labour",
    "Carmarthen East and Dinefwr": "Plaid Cymru",
    "Clacton": "Conservative",
    "South Norfolk": "Conservative",
    "Dover": "Conservative",
    "Derbyshire Dales": "Conservative",
    "Sutton and Cheam": "Conservative",
    "Norwich North": "Conservative",
    "Dumfries and Galloway": "Conservative",
    "Coatbridge, Chryston and Bellshill": "Scottish National",
    "Eastleigh": "Conservative",
    "Worcester": "Conservative",
    "Ilford South": "Labour",
    "Saffron Walden": "Conservative",
    "City of Chester": "Labour",
    "Eltham": "Labour",
}