TOP_PLACES = [
    "London", "Birmingham", "Glasgow", "Liverpool", "Bristol", "Manchester", "Sheffield", "Leeds", "Edinburgh", "Leicester",
    "Coventry", "Bradford", "Cardiff", "Belfast", "Nottingham", "Kingston upon Hull", "Newcastle upon Tyne", "Stoke-on-Trent",
    "Southampton", "Derby", "Portsmouth", "Brighton", "Plymouth", "Northampton", "Reading", "Luton", "Wolverhampton", "Bolton",
    "Aberdeen", "Bournemouth", "Norwich", "Swindon", "Swansea", "Milton Keynes", "Southend-on-Sea", "Middlesbrough", "Peterborough",
    "Sunderland", "Warrington", "Huddersfield", "Slough", "Oxford", "York", "Poole", "Ipswich", "Telford", "Cambridge", "Dundee",
    "Gloucester", "Blackpool", "Birkenhead", "Watford", "Sale", "Colchester", "Newport", "Solihull", "High Wycombe", "Exeter",
    "Gateshead", "Blackburn", "Cheltenham", "Maidstone", "Chelmsford", "Salford", "Basildon", "Doncaster", "Basingstoke", "Worthing",
    "Eastbourne", "Crawley", "Rochdale", "Rotherham", "Stockport", "Gillingham", "Sutton Coldfield", "Woking", "Wigan", "Lincoln",
    "Oldham", "Wakefield", "St Helens", "Worcester", "Hemel Hempstead", "Bath", "Preston", "Rayleigh", "Barnsley", "Stevenage",
    "Hastings", "Southport", "Darlington", "Bedford", "Halifax", "Hartlepool", "Chesterfield", "Nuneaton", "Grimsby", "Weston-super-Mare",
    "Chester", "St Albans", "Harlow", "Guildford", "Aylesbury", "Stockton-on-Tees", "Dudley", "Bracknell", "Derry/Londonderry", "Redditch",
    "Batley", "Scunthorpe", "Burnley", "Eastleigh", "Mansfield", "Chatham", "Bury", "Newcastle-under-Lyme", "West Bromwich", "Paisley",
    "South Shields", "Burton upon Trent", "Rugby", "East Kilbride", "Carlisle", "Harrogate", "Gosport", "Grays", "Shrewsbury", "Ashford",
    "Tamworth", "Crewe", "Lowestoft", "Atherton", "Walsall", "Stafford", "Cannock", "Bognor Regis", "Walton-on-Thames", "Tynemouth",
    "Bamber Bridge", "Maidenhead", "Washington", "Paignton", "Filton", "Rochester", "Farnborough", "Dewsbury", "Loughborough", "Newtownabbey",
    "Margate", "Stourbridge", "Craigavon", "Hereford", "Widnes", "Canterbury", "Taunton", "Runcorn", "Wrexham", "Scarborough", "Bangor",
    "Ellesmere Port", "Wallasey", "Corby", "Royal Tunbridge Wells", "Kettering", "Halesowen", "Aldershot", "Littlehampton", "Bebington",
    "Gravesend", "Kidderminster", "Livingston", "Barry", "Royal Leamington Spa", "Macclesfield", "Christchurch", "Altrincham", "Weymouth",
    "Brentwood", "Hamilton", "Ewell", "Clacton-on-Sea", "Keighley", "Beeston", "Dunfermline", "Willenhall", "Folkestone", "Smethwick",
    "Esher", "Sittingbourne", "Wellingborough", "Bootle", "Durham", "Welwyn Garden City", "Bloxwich", "Neath", "Cumbernauld", "Kingswinford",
    "Lancaster", "Shoreham-by-Sea", "Torquay", "Horsham", "Carlton", "Kirkcaldy", "Crosby", "King's Lynn", "Horndean", "Hinckley", "Swadlincote",
    "Winchester", "Bridgend", "Yeovil", "Sutton-in-Ashfield", "West Bridgford", "Perth", "Havant", "Inverness", "Ashton-under-Lyne", "Banbury",
    "Cwmbrân", "Cheshunt", "Northwich", "Ayr", "Kilmarnock", "Wokingham", "Salisbury", "Andover", "Lisburn", "Boston", "Hatfield", "Llanelli",
    "Merthyr Tydfil", "Wallsend", "Tipton", "Grantham", "Dover", "Barrow-in-Furness", "Bexhill-on-Sea", "Lytham St Annes", "Bridgwater", "Middleton",
    "Coatbridge", "Hoddesdon", "Braintree", "Fareham", "Trowbridge", "Worksop", "Kirkby", "Jarrow", "Greenock", "Ramsgate", "Urmston", "Castleford",
    "Bury St Edmunds", "Caerphilly", "Newbury", "Leighton Buzzard", "Fleet", "Tonbridge", "Eccles", "Great Yarmouth", "Herne Bay", "Bishop's Stortford",
    "Leyland", "Ilkeston", "Camberley", "Abingdon-on-Thames", "Arnold", "Newark-on-Trent", "Long Eaton", "Aldridge", "Bletchley", "Cleethorpes", "Blyth",
    "Canvey Island", "Chorley", "Glenrothes", "Prescot", "Great Malvern", "Port Talbot", "Longbenton", "Haywards Heath", "Stirling", "Chester-le-Street",
    "Woodley", "Redcar", "Borehamwood", "Airdrie", "Wilmslow", "Redhill", "Whitley Bay", "Accrington", "Hitchin", "Coalville", "Denton", "Wath-upon-Dearne",
    "Chippenham", "Chadderton", "Falkirk", "Exmouth", "Fulwood", "Rowley Regis", "Hyde", "Bromsgrove", "Romiley", "Spalding", "Bridlington", "Hucknall",
    "Billericay", "Skelmersdale", "Epsom", "Billingham", "Wickford", "Letchworth Garden City", "Wisbech", "Stroud", "Irvine", "Pudsey", "Brighouse", "Lichfield",
    "Whitstable", "Morecambe", "Dumfries", "Glossop", "Dunstable", "Leatherhead", "St Neots", "Bicester", "Warwick", "Loughton", "Motherwell", "Bilston", "Windsor",
    "Barnstaple", "Rushden", "Burgess Hill", "Chichester", "Brierley Hill", "Deal", "Sevenoaks", "Sedgley", "Radcliffe", "Bedworth", "Rutherglen", "Harpenden",
    "Beverley", "Pontypridd", "Aberdare", "Winsford", "Nelson", "Yate", "Witney", "Wishaw", "East Grinstead", "Pontefract", "Weybridge", "Didcot", "Heywood",
    "Northfleet", "Morley", "Stratford-upon-Avon", "Totton", "Ballymena", "Heswall", "Penarth", "Kendal", "Cambuslang", "Stanford-le-Hope", "Pontypool", "Hertford",
    "Shipley", "Ashford", "Burntwood", "Ashton-in-Makerfield", "Kirkby-in-Ashfield", "Colwyn Bay", "Bearsden", "Egham", "Newtownards", "Ashington", "Carrickfergus",
    "Farnworth", "Haverhill", "Stretford", "Darwen", "Melton Mowbray", "Evesham", "Frome", "Cramlington", "Thetford", "Bentley", "Ditton", "Farnham", "Stalybridge",
    "Ferndown", "Newton Abbot", "Peterlee", "Newry", "Staines-upon-Thames", "Bushey", "Witham", "Newton Mearns", "Hedge End", "Heanor", "Clydebank", "Portishead",
    "Congleton", "Kidsgrove", "Thatcham", "Ormskirk", "Rhyl", "Huntingdon", "Thornaby-on-Tees", "Newton Aycliffe", "Newport", "Maghull", "St Austell", "Fleetwood",
    "Corsett", "Plymstock", "Swinton", "Oldbury", "Market Harborough", "Bishop Auckland", "Wednesfield", "Cheadle Hulme", "Rickmansworth", "Stubbington", "Horley",
    "Skegness", "Wombwell", "Daventry", "Ryde", "Elgin", "Gorleston-on-Sea", "Hindley", "Coleraine", "Broadstairs", "Windlesham", "Rugeley", "Amersham", "Felixstowe",
    "Golborne", "Droylsden", "Rawtenstall", "Blackwood", "Westhoughton", "Belper", "Burnham-on-Sea", "Falmouth", "Arbroath", "Droitwich Spa", "Newton-le-Willows",
    "Chesham", "Whitehaven", "Bishopbriggs", "Potters Bar", "Seaford", "Sudbury", "Godalming", "Reigate", "Formby", "Antrim", "Alfreton", "Coseley", "Royton", "Retford",
    "Clifton", "Caterham", "Bathgate", "Bingley", "Gainsborough", "Buxton", "Chapeltown", "Seaham", "Renfrew", "Swanscombe", "Ingleby Barwick", "Workington", "Holmfirth",
    "Goole", "Truro", "Hailsham", "Camborne", "Newquay", "Crowborough", "Ossett", "Normanton", "Maldon", "South Ockenden", "Stanley", "March", "Kenilworth", "Gatley",
    "Berkhamsted", "Walkden", "Kirkintilloch", "Ampthill", "Stowmarket", "Dereham", "Kempston", "Whitefield", "Dukinfield", "Clevedon", "Brownhills", "Redruth", "Gerrards Cross",
    "Chalfont St Peter", "Newmarket", "Minster", "Dronfield", "Tewkesbury", "Harwich", "Musselburgh", "Sandhurst", "Dorchester", "Dumbarton", "Stamford", "Faversham", "New Milton",
    "Hythe", "Dinnington", "Irlam", "Stourport-on-Severn", "Darlaston", "Belshill", "Ely", "Buckley", "Biggleswade", "Portslade-by-Sea", "Tiverton", "Peacehaven", "Ware", "Earl Shilton",
    "Leek", "Oswestry", "Bideford", "Mirfield", "Ripley", "Ystrad Mynach", "Emsworth", "Horwich", "Hazel Grove", "Hebburn", "Omagh", "Melksham", "Kesgrave", "Yarm-Eaglescliffe", "Thornton",
    "Rothwell", "Sandbach", "Horsforth", "Wantage", "Wednesbury", "Frimley", "Peterhead", "Alton", "Waltham Abbey", "Selby", "Yeadon", "Eastwood", "Rawmarsh", "Spennymoor", "Devizes",
    "Adwick-le-Street", "Colne", "Maesteg", "Failsworth", "Larne", "Mansfield Woodhouse", "Cobham", "Litherland", "Great Wyrley", "Marple", "Bangor", "Shaw", "Hoyland", "Rochford", "Biddulph",
    "Ebbw Vale", "Liversedge", "Calne", "Nantwich", "Sleaford", "Houghton Regis", "Tonypandy", "Lewes", "Westbury", "Warminster", "Poulton-le-Fylde", "Ramsbottom", "Addlestone", "Dorking",
    "Barrhead", "St Andrews", "Bonnyrigg", "Hale", "Romsey", "Bramhall", "Shotton", "Guisborough", "Keynsham", "Swanley", "St Ives", "Northallerton", "Louth", "Bedlington", "Gorseinon",
    "Brixham", "Cirencester", "Prestatyn", "Royston", "Blantyre", "North Hykeham", "Connah's Quay", "Saffron Walden", "Banbridge", "Grangemouth", "Tyldesley", "Heysham", "Haydock", "Stone",
    "Ryton", "Aberystwyth", "Carterton", "Stapleford", "Kilwinning", "Haslingden", "Hartley", "Longfield", "Maltby", "Penzance", "Uckfield", "Wimborne Minster", "South Woodham", "Ferrers",
    "Carmarthen", "Ripon", "Whickham", "Elland", "Bourne", "Penicuik", "Johnstone", "Nailsea", "Clitheroe", "Conisborough", "South Normanton", "Saltash", "South Hayling", "Lymington", "Baildon",
    "Viewpark", "Bodmin", "Matlock", "Tadley", "Teignmouth", "Porthcawl", "Knaresborough", "Dursley", "Mexborough", "Taverham", "Erskine", "Penrith", "Broxburn", "Hythe", "Staveley", "Mildenhall",
    "Llandudno", "Dundonald", "Frampton Cotterell", "Winterbourne", "Kidlington", "Wymondham", "Petersfield", "Neston", "Swallownest", "Poynton", "Skipton", "Ilkley", "Bishop's Cleeve", "Haverfordwest",
    "Bordon", "Newtownbreda", "Tredegar", "Risca", "West Kirby", "Cottingham", "Blaydon", "Newport Pagnell", "Marlow", "Buckingham", "Borrowstounness", "Garforth", "Armagh", "Larkhall", "Prestwick",
    "Troon", "Morpeth", "Flint", "Beaconsfield", "Chertsey", "Port Glasgow", "Yateley", "Porth", "Armthorpe", "Cowes", "Knottingley", "Hessle", "Ashtead", "Alloa", "Market Deeping", "Pyle", "Dunscroft",
    "Dungannon", "Ringwood", "Otley", "Crowthorne", "Houghton-le-Spring", "Forfar", "Beccles", "Brackley", "Middlewich", "Church Village", "Newhaven", "Innsworth", "Shepshed", "Milford Haven", "Bacup",
    "Syston", "Cheadle", "Ashby-de-la-Zouch", "Enniskillen", "Chard", "Rosyth", "Narborough", "Verwood", "Hawick", "Hurstpierpoint", "Uppermill", "Street", "Corsham", "Helensburgh", "Inverurie", "Wombourne",
    "Oxted", "Blackfield", "Bridport", "Llantrisant", "Mayfield", "Alsager", "Midsomer Norton", "Birstall", "Chorleywood", "Standish", "Berwick-upon-Tweed", "Whetstone", "Tilbury", "Abergavenny", "Dalkieth",
    "Haslemere", "Rhosllanerchrugog", "Saltdean", "Carluke", "Clay Cross", "New Rossington", "Knutsford", "Sheerness", "Linlithgow", "Mountsorrel", "Rhondda", "Brough", "Newport", "Fraserburgh", "Sidmouth",
    "Strabane", "Uttoxeter", "Driffield", "Whitby", "Galashiels", "Ince-in-Makerfield", "Whittlesley", "Milngavie", "Lees", "Stocksbridge", "Bridgnorth", "Dawlish", "Pontardawe", "Royal Wootton Bassett", "Cudworth",
    "Kirkham", "Catterick Garrison", "Heckmondwike", "Saltcoats", "New Mills", "Mablethorpe", "Little Lever", "Armadale", "Guiseley", "North Walsham", "Tavistock", "Wellington", "Llandudno Junction", "Chepstow",
    "Walton-on-the-Naze", "Hetton-le-Hole", "Blandford Forum", "Giffnock", "Westhill", "Tring", "Market Drayton", "Littleborough", "Tranent", "Halstead", "Todmorden", "Montrose", "Limavady", "Minehead", "Bolsover",
    "Thorne", "Lymm", "Downham Market", "Thornbury", "Cleckheaton", "Sandown", "Southwick", "Sarn Aberkenfig", "Bryncoch", "Bargoed", "Helston", "Sandy", "Haxby", "Shirebrook", "Ivybridge", "Kimberley", "Holyhead",
    "Codsall", "Barton-upon-Humber", "Featherstone", "Cowdenbeath", "Henley-on-Thames", "Woodbridge", "Caldicot", "Cookstown", "Gillingham", "Thame", "Snodland", "Attleborough", "Honiton", "Desbrorough", "Leominster",
    "Oswaldtwistle", "Southborough", "Hexham", "Carnoustie", "Ross-on-Wye", "Ulverston", "Holywood", "Newtown", "Atherstone", "Tidworth", "Cinderford", "Mountain Ash", "Kearsley", "Largs", "Cheadle", "Epping", "Stonehaven",
    "Wetherby", "Amesbury", "Oakham", "Mossley", "Ilfracombe", "Immingham", "Larbert", "Prudhoe", "Wells", "Chigwell", "Chatteris", "South Elmsall", "Banstead", "Downpatrick", "Whitburn", "Kingsteignton", "Great Harwood",
    "Hoylake", "Annfield Plain", "Diss", "Methill", "Northam", "Abertillery", "Cleveleys", "Catshill", "Penistone", "Shepton Mallet", "Androssan", "Baldock", "Swanage", "New Ollerton", "Platts Bridge", "Royston", "Sawbridgeworth",
    "Waltham Cross", "Polegate", "Ystradgynlais", "Thirsk", "Ludlow", "Lutterworth", "Horbury", "Monmouth", "Selsey", "Ponteland", "Prestonpans", "St Blazey", "Ballymoney", "Gourock", "North Ascot", "Penryn", "Stranraer",
    "Chadwell St Mary", "Brierfield", "Barnoldswick", "Milnrow", "Bingham", "Ellon", "Cranleigh", "Soham", "Westergate", "Mold", "Radstock", "Forres", "Kilsyth", "Cambourne", "Dalgety Bay", "Whitchurch", "Brandon", "Nairn",
    "New Romney", "Polesworth", "Woodingdean", "Ballyclare", "Holywell", "Sandiacre", "Shildon", "Adlington", "Clarkston", "North Walney", "Caernarfon", "Sherborne", "Stenhousemuir", "Kippax", "Towcester", "Pembroke Dock",
    "Bulford Camp", "Warlingham", "St Ives", "Newbridge", "Bradford on Avon", "Tonyrefail", "Crook", "Kinmel Bay", "Maryport", "Brandon", "Wideopen", "Burton Latimer", "Liskeard", "Ferryhill", "Watton", "Yaxley", "Dunblane",
    "Killamarsh", "Market Warsop", "Cockermouth", "Hemsworth", "South Queensferry", "Pencoed", "North Wingfield", "Abergele", "Pontarddulais", "Sileby", "Pontllanfraith", "Worsbrough", "Stevenston", "Shanklin", "Frodsham",
    "Tiptree", "Lydney", "Southwater", "Ledbury", "Worsley", "Haddington", "Aveley", "Portlethen", "Comber", "Bonhill", "Lanark", "Leven", "Dunbar", "Blairgowrie", "Cupar", "Longton", "Thurnscoe", "Pocklington", "Burscough",
    "Broughton Astley", "Peebles", "Caister-on-Sea"
]