# Generated by Django 5.2.8 on 2025-11-06 18:51

from django.db import migrations


def populate_slug_redirects(apps, schema_editor):
    SlugRedirect = apps.get_model('givefood', 'SlugRedirect')
    
    # Data from OLD_FOODBANK_SLUGS in givefood/const/general.py
    old_foodbank_slugs = {
        "angus": "dundee-angus",
        "dundee": "dundee-angus",
        "lifeshare": "lifeshare-manchester",
        "galashiels": "galashiels-and-area",
        "bristol-north": "north-bristol-south-gloucestershire",
        "feed": "st-albans-and-district",
        "hillingdon/hayes-st-anselm": "st-anselm",
        "b30": "b30-south-birmingham",
        "kingfisher": "north-solihull",
        "bethnal-green": "bow/bethnal-green",
        "swansea/st-thomas-church": "st-thomas",
        "skye": "skye-lochalsh",
        "cromer-district": "north-norfolk",
        "blandford": "nourish",
        "abergele-district/kinmel-bay-church": "kinmel-bay-church",
        "vauxhall": "lambeth-south-croydon",
        "ballymena/ballymena-north": "ballymena-north",
        "quinton-oldbury": "quinton",
        "chalk-farm": "kentish-town",
        "cupboard-love": "bridport",
        "glastonbury": "glastonbury-street",
        "hollingdean": "hollingdean-fiveways",
        "bay": "the-bay",
        "st-pauls-centre": ":st-pauls",
        "central-southwark-community-hub": "spring-community-hub",
        "clyde-avon-nethan": "larkhall-district",
        "norwood-brixton": "lambeth-south-croydon",
        "southbourne": "bournemouth/southbourne",
        "east-ayrshire": "ayrshire-east",
        "falkirk/donationpoint/asda-superstore-stenhousemuir": "klsb/donationpoint/asda-stenhousemuir",
        "newcastle-west-end": "newcastle",
        "kings-centre-honiton": "honiton",
        "helston-lizard": "helston-the-lizard",
        "restore-northampton": "northampton",
        "wells-vineyard": "wells",
        "lambeth-south-croydon": "lambeth-croydon",
        "ivybridge": "ivybridge-district",
        "waterloo": "lambeth-croydon",
        "lowestoft": "lowestoft-district",
        "skelmersdale": "skelmersdale-district",
        "keynsham": "bath-keynsham-somer-valley",
        "bath": "bath-keynsham-somer-valley",
        "somer-valley": "bath-keynsham-somer-valley",
        "stretford": "trafford-north",
        "durham": "county-durham",
        "hunstanton-and-district": "hunstanton-district",
        "redcar": "redcar-area",
        "cpr": "transformation",
        "belfast-south-west": "south-west-belfast",
        "yarmouth-magdalen": "great-yarmouth",
        "stow-park-community-centre": "newport-district",
        "godmanchester": "godmanchester-huntingdon",
    }
    
    # Bulk create all redirects
    slug_redirects = [
        SlugRedirect(old_slug=old_slug, new_slug=new_slug)
        for old_slug, new_slug in old_foodbank_slugs.items()
    ]
    SlugRedirect.objects.bulk_create(slug_redirects)


def reverse_populate_slug_redirects(apps, schema_editor):
    SlugRedirect = apps.get_model('givefood', 'SlugRedirect')
    SlugRedirect.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('givefood', '0001_add_slugredirect_model'),
    ]

    operations = [
        migrations.RunPython(populate_slug_redirects, reverse_populate_slug_redirects),
    ]
